### ISSUE TITLE
Add it mplug script directory

### ISSUE THREAD

**Issue by z8512** [johndovern/ani-man#1]
Mplug is like a package manager but for mpv scripts.
Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by johndovern** [comment]
I've submitted a [PR](https://github.com/Nudin/mpv-script-directory/pull/4) on that repo and I have [added](https://github.com/johndovern/ani-man/commit/c66443ed78ef3eadcd29fbcb2cf43f34d680ff90) an `-S, --setup` flag to complete the installation process for MPlug users.

I didn't know about this but it seems pretty useful. Thank you.
